# Generated by Django 3.2.3 on 2021-06-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='directory',
            field=models.CharField(default="os.getenv('HOME') + '/.vaults'", max_length=200),
        ),
        migrations.AddField(
            model_name='vault',
            name='filename',
            field=models.CharField(default='vault', max_length=200),
        ),
        migrations.DeleteModel(
            name='VaultRecords',
        ),
    ]
