# Generated by Django 3.2.3 on 2021-06-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_backend', '0002_auto_20210621_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='directory',
            field=models.CharField(default='/home/sharan/.vaults', max_length=200),
        ),
    ]
