# Generated by Django 3.2.3 on 2021-06-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault_backend', '0003_alter_vault_directory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vault',
            name='id',
        ),
        migrations.AddField(
            model_name='vault',
            name='number',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
